export {default as DefaultPage} from './src/component/defaultPage/DefaultPage'
export {default as Header} from './src/component/header/Header'
export {default as Footer} from './src/component/footer/Footer'
export {default as Homepage} from './src/component/homepage/HomePage'
export {default as Login} from './src/component/login/Login'
export {default as SignUp} from './src/component/signup/Signup'
export {default as ProfileMain} from './src/component/profile/ProfileMain'
export {default as ChangePasswordMain} from './src/component/change-password/ChangePasswordMain'
export {default as PrivacyPolicyMain} from './src/component/privacy-policy/PrivacyPolicyMain'
export {default as HelpSupportMain} from './src/component/help-support/HelpSupportMain'
export {default as WishlistListMain} from './src/component/wishlist/WishlistMain'
export { default as CategoryMain} from './src/component/category-page/CategoryMain'
export { default as CartMain } from './src/component/cart/CartMain'
export { default as CheckoutMain} from './src/component/checkout/CheckoutMain'
export {default as WalletMain} from './src/component/wallet/WalletMain'
export {default as ProductMain} from './src/component/product/ProductMain'
export {default as InternetOff} from './src/component/internetoff/InternetOff'